<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.11.0" name="E_ROLLER" tilewidth="16" tileheight="16" tilecount="3" columns="0">
 <grid orientation="orthogonal" width="1" height="1"/>
 <tile id="0" type="E_ROLLER">
  <properties>
   <property name="state" propertytype="frames" value="SPNEUTRAL0"/>
  </properties>
  <image source="images/enemy000.png" width="16" height="16"/>
 </tile>
 <tile id="1" type="E_ROLLER">
  <properties>
   <property name="state" propertytype="frames" value="SPNEUTRAL1"/>
  </properties>
  <image source="images/enemy001.png" width="16" height="16"/>
 </tile>
 <tile id="2" type="E_ROLLER">
  <properties>
   <property name="state" propertytype="frames" value="SPNEUTRAL2"/>
  </properties>
  <image source="images/enemy002.png" width="16" height="16"/>
 </tile>
</tileset>
