<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.11.0" name="T_BGTILES" tilewidth="16" tileheight="16" tilecount="6" columns="0">
 <grid orientation="orthogonal" width="1" height="1"/>
 <tile id="0">
  <image source="images/tile000.png" width="16" height="16"/>
 </tile>
 <tile id="1">
  <image source="images/tile001.png" width="16" height="16"/>
 </tile>
 <tile id="2">
  <image source="images/tile002.png" width="16" height="16"/>
 </tile>
 <tile id="3">
  <image source="images/tile003.png" width="16" height="16"/>
 </tile>
 <tile id="4">
  <image source="images/tile004.png" width="16" height="16"/>
 </tile>
 <tile id="6">
  <image source="images/tile005.png" width="16" height="16"/>
 </tile>
</tileset>
